### ISSUE TITLE
It pins a tab, even if doubleclicked by right/middle mouse buttons

### ISSUE THREAD

**Issue by Drugoy** [supahgreg/easy-app-tabs#1]
I think it's wrong, as doubleclick usually means double left click, not a double any_button click.

**Comment by supahgreg** [comment]
Thanks, this has been taken care of with 1e80737e28bd9db8d494605740f7a304fffe1e02.  The new version ("2") should be on AMO shortly... waiting for it to be reviewed, I believe.

**Comment by Drugoy** [comment]
Thank you for a fast fix, I've tested it and it works good now.
