### ISSUE TITLE
Not working in Private Browsing mode

### ISSUE THREAD

**Issue by loosemoose613** [supahgreg/easy-app-tabs#10]
Just updated from FF 32.0.1 to 32.0.3 and now Easy App Tabs 7 no longer works in Private Browsing mode.

**Comment by supahgreg** [comment]
Seems to be due to the switch to the Add-on SDK in version 7.  I believe I'll just need to update `package.json` to allow execution in private browsing mode.  I'll get a new version built when I get home later today.  Thanks for the report!

**Comment by supahgreg** [comment]
Should be resolved by version 8, which I've just submitted for approval on AMO.

Closed by 9a7bd2742c64154b9f24009b4eb49813a5428073

**Comment by loosemoose613** [comment]
Thank you!! It is working again :) You rock.
