### ISSUE TITLE
external link in external tabs

### ISSUE THREAD

**Issue by carl0s** [supahgreg/easy-app-tabs#2]
What about implementing a configurable set of apptabs which lets you open external links into the page into new tabs? Considering the use case "app tab with facebook" external links should be always open externally because you do want to preserve the app tab content.
This applies in almost every app tabs.

Thanks!

**Comment by supahgreg** [comment]
I agree it would be a good idea to have something like that, but it is beyond the scope of what I'm wanting to do with this add-on.  Thanks, though!
