### ISSUE TITLE
Suggestion: Ctrl+Click

### ISSUE THREAD

**Issue by zants** [supahgreg/easy-app-tabs#3]
I tend to accidentally double-click a tab when I don't mean to change its status to an app tab.

A feature from an old Firefox extension was Ctrl key+Left click to change the tab's status to an app tab, and I think it would be a great addition to Easy App Tabs as an option instead of double-click.

**Comment by supahgreg** [comment]
I've added `ctrl + primary click` toggling to the just-released version 4.  I'll look into making the toggle method a preference for the next release.
