### ISSUE TITLE
Double clicking on X

### ISSUE THREAD

**Issue by joetomato** [supahgreg/easy-app-tabs#5]
I have Tree Style Tab installed, and this. (FF 7.0.1 on Windows XP.)  When I click on an inactive tab, and then immediately click on the X to close that tab, it's detecting it as a double click, and instead of closing the tab, makes it into an app tab.

Just a minor annoyance, but just thought I'd point it out.

Excellent extension, by the way. :)

**Comment by supahgreg** [comment]
Thanks for the report!  I believe this should be fixed in v5, which I've uploaded to AMO.
