### ISSUE TITLE
Firefox closes the wrong tab while closing multiple pages

### ISSUE THREAD

**Issue by Mighty-Moe** [supahgreg/easy-app-tabs#8]
The message is a copy of https://support.mozilla.org/uk/questions/958341#answer-433835

It's really tricky to describe... Ok, let's say i want to search firefox logo via google images. I found a lot of interesting results and opened them in different tabs. Now i found one pic that i really like and want to close tabs i dont need anymore. I'm not changing active tab and just pressing crosses to close desired inactive tabs. I care for my time and automatically doing it fast. But after 2 tabs closed, third tab not only closes itself, but it makes my active tab close too!

This happens no matter what pages i use, how many are open, memory usage, etc. It just happens no matter what. There are only 2 conditions i need to meet: - Close tabs that are inactive - Do it fast

I'd really appreciate some help with my problem because the tab that usually accidentally crash is the tab with a lot of edited text. You can imagine how disappointing it may be.

Thank you.

**Comment by supahgreg** [comment]
Thanks, I've pushed version 6 to addons.mozilla.org.  Still pending a review, but you can grab it @ https://addons.mozilla.org/en-US/firefox/addon/easy-app-tabs/versions/

**Comment by Mighty-Moe** [comment]
Thx, supahgreg, seems like everything is fine with latest version. Cheers!
